# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pranav Mokali
email: pranav@moktali.io
description: Eat. Code. Bike.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pranav.moktali.io" # the base hostname & protocol for your site
twitter:
  username: mokpro
github:
  username:  mokpro

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-github-metadata

theme: jekyll-theme-leap-day